# Generated by Django 4.0.6 on 2023-06-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_remove_user_dob_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
