# Generated by Django 4.0.6 on 2023-06-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0006_remove_user_mobile_number_user_age_user_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('vaccination_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinationcentre')),
            ],
        ),
    ]
