# Generated by Django 4.0.6 on 2023-06-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0007_appliedvaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationcentre',
            name='slots_per_day',
            field=models.IntegerField(default=10),
        ),
    ]
