# Generated by Django 4.0.6 on 2023-06-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0008_vaccinationcentre_slots_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationcentre',
            name='dosages_available',
            field=models.IntegerField(default=0),
        ),
    ]
