# Generated by Django 4.0.6 on 2023-06-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0009_vaccinationcentre_dosages_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
