# Generated by Django 4.0.6 on 2023-06-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0010_remove_user_age_remove_user_dob_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mpin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
