# Generated by Django 4.0.6 on 2023-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0014_remove_vaccinationcentre_dosages_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationcentre',
            name='dosages_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccinationcentre',
            name='slots_per_day',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='vaccinationcentre',
            name='working_hours',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='vaccinationslot',
            name='available_slots',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='vaccinationcentre',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccinationcentre',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccinationslot',
            name='vaccination_centre',
            field=models.CharField(max_length=255),
        ),
    ]
