# Generated by Django 4.0.6 on 2023-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0016_alter_vaccinationcentre_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationcentre',
            name='working_hours',
            field=models.CharField(max_length=100),
        ),
    ]
