# Generated by Django 4.0.6 on 2023-06-25 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0018_alter_vaccinationcentre_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedvaccination',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='appliedvaccination',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='appliedvaccination',
            name='vaccination_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='appliedvaccination',
            name='vaccination_type',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
